import type { Metadata } from "next";

import "./globals.css";



export const metadata: Metadata = {
  title: "wsa-project",
  description: "Generated by create next app",
};





export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en" 
      >
      <body className="p-0 m-0">{children}</body>
    </html>
  );
}
