import type { Metadata } from "next";
import "./globals.css";
import BodyBackground from "./ui/components/BodyBackground";


export const metadata: Metadata = {
  title: "wsa-project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
     

      <body className="p-0 m-0">
        <BodyBackground />
        {children}
      </body>
    </html>
  );
}